#ifndef EXPERIMENTAL_USERS_EYTANKIDRON_PLATFORMS_HELLO_WORLD_LIB_H_
#define EXPERIMENTAL_USERS_EYTANKIDRON_PLATFORMS_HELLO_WORLD_LIB_H_

#include <string>

std::string get_hello();

#endif  // EXPERIMENTAL_USERS_EYTANKIDRON_PLATFORMS_HELLO_WORLD_LIB_H_
